_wandb:
    value:
        cli_version: 0.24.0
        e:
            hd20idcuwqq6n4y8mnyqmmzi2jemdk95:
                codePath: /workspaces/Trainers/MNIST/CNN/model1/wandbtest.ipynb
                codePathLocal: wandbtest.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "1081101176832"
                        used: "48937029632"
                email: g.aravindadithya@gmail.com
                executable: /venv/main/bin/python
                git:
                    commit: 5de67b06253c0d04de1d46d69578b4ce8fdc919e
                    remote: https://github.com/aravindadithya/Trainers.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-af33d267-e475-2166-48c2-2823b7ca2b60
                host: 268c70302458
                memory:
                    total: "8009216000"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /workspaces/Trainers/MNIST/CNN/model1/wandbtest.ipynb
                python: CPython 3.12.12
                root: /workspaces/Trainers/MNIST/CNN/model1
                startedAt: "2026-01-18T17:50:46.652217Z"
                writerId: hd20idcuwqq6n4y8mnyqmmzi2jemdk95
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 2
                - 13
                - 14
                - 16
                - 62
            "4": 3.12.12
            "5": 0.24.0
            "8":
                - 1
            "12": 0.24.0
            "13": linux-x86_64
learning_rate:
    value: 0.1
loss_function:
    value: CrossEntropyLoss
model_architecture:
    value: ConvNet
optimizer:
    value: SGD
weight_decay:
    value: 0
