_wandb:
    value:
        cli_version: 0.24.0
        e:
            ax2xm920qlbgdh9z5xnw3la0563230vd:
                codePath: /workspaces/Trainers/MNIST/FC/model1/wandbtest.ipynb
                codePathLocal: wandbtest.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "1081101176832"
                        used: "63526957056"
                email: g.aravindadithya@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: 5f12bd0faaba67c5e059ac9881fbefb0c9c2648b
                    remote: https://github.com/aravindadithya/Trainers.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-af33d267-e475-2166-48c2-2823b7ca2b60
                host: eeffdba277a9
                memory:
                    total: "8009216000"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /workspaces/Trainers/MNIST/FC/model1/wandbtest.ipynb
                python: CPython 3.10.12
                root: /workspaces/Trainers/MNIST/FC/model1
                startedAt: "2026-01-16T19:43:36.644909Z"
                writerId: ax2xm920qlbgdh9z5xnw3la0563230vd
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 5
                - 13
                - 14
                - 16
                - 62
            "4": 3.10.12
            "5": 0.24.0
            "8":
                - 1
            "12": 0.24.0
            "13": linux-x86_64
epochs:
    value: 10
learning_rate:
    value: 0.1
loss_function:
    value: CrossEntropyLoss
model_architecture:
    value: Net
optimizer:
    value: SGD
weight_decay:
    value: 0
